modLoader="javafml"
loaderVersion="[38,)"
license="MIT"
[[mods]]
modId="askgptmod"
version="${file.jarVersion}"
displayName="AskGPT Mod"
logoFile="examplemod.png"
credits="Mod developed by Instinct"
authors="Instinct"
description='''
Mod by Instinct
'''

[[dependencies.askgptmod]] 
    modId="forge"
    mandatory=true 
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.askgptmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
